//! Build script for UniFFI bindings
//!
//! With proc-macros, we just need to enable the uniffi build feature.

fn main() {
    // With proc-macros (uniffi::setup_scaffolding!), no UDL file is needed.
    // The scaffolding is generated by the macro at compile time.
    println!("cargo:rerun-if-changed=src/lib.rs");
}
