//
//  HiveFFI.swift
//  HiveTest
//
//  Placeholder for UniFFI-generated Rust bindings.
//  The actual bindings will be generated when the xcframework is built.
//  For now, the app uses mock data for demonstration.
//

import Foundation

// This file is a placeholder. The real bindings are in hive_apple_ffi.swift
// which is generated by the build-ios.sh script using UniFFI.
//
// To integrate the real bindings:
// 1. Run ./build-ios.sh to build the Rust library and generate bindings
// 2. Add the HiveFFI.xcframework to your Xcode project
// 3. Remove this placeholder and use the generated hive_apple_ffi.swift
