#!/bin/bash
# Lab 4 Backend Comparison Framework
#
# Unified execution script for comparing Ditto and Automerge backends.
# Uses backend-agnostic topologies generated by generate-lab4-hierarchical-topology.py.
#
# Usage:
#   ./run-lab4-comparison.sh                           # Run full matrix
#   ./run-lab4-comparison.sh --backend automerge       # Run all automerge tests
#   ./run-lab4-comparison.sh --nodes 384               # Run all backends at 384n
#   ./run-lab4-comparison.sh --backend ditto --nodes 96 --bandwidth 1gbps  # Single test
#   ./run-lab4-comparison.sh --dry-run                 # Show what would run
#   ./run-lab4-comparison.sh --cleanup-only            # Clean up environment

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

source ./test-common.sh

# Default configuration from lab-config-matrix.yaml
CONFIG_FILE="${SCRIPT_DIR}/lab-config-matrix.yaml"
BACKENDS=("ditto" "automerge")
NODE_COUNTS=(24 48 96 384)
BANDWIDTHS=("1gbps" "100mbps" "1mbps" "256kbps")
TEST_DURATION_SECS=120
RESULTS_BASE_DIR="/work/hive-sim-results"

# Command line arguments
ARG_BACKEND=""
ARG_NODES=""
ARG_BANDWIDTH=""
DRY_RUN=false
CLEANUP_ONLY=false
CONTINUE_ON_ERROR=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --backend)
            ARG_BACKEND="$2"
            shift 2
            ;;
        --nodes)
            ARG_NODES="$2"
            shift 2
            ;;
        --bandwidth)
            ARG_BANDWIDTH="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --cleanup-only)
            CLEANUP_ONLY=true
            shift
            ;;
        --continue-on-error)
            CONTINUE_ON_ERROR=true
            shift
            ;;
        --duration)
            TEST_DURATION_SECS="$2"
            shift 2
            ;;
        --help|-h)
            echo "Lab 4 Backend Comparison Framework"
            echo ""
            echo "Usage:"
            echo "  $0 [options]"
            echo ""
            echo "Options:"
            echo "  --backend <ditto|automerge>  Run only this backend"
            echo "  --nodes <24|48|96|384>       Run only this node count"
            echo "  --bandwidth <1gbps|...>      Run only this bandwidth"
            echo "  --duration <secs>            Test duration (default: 120)"
            echo "  --dry-run                    Show what would run without executing"
            echo "  --cleanup-only               Clean up environment and exit"
            echo "  --continue-on-error          Continue running tests even if one fails"
            echo "  --help                       Show this help"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Apply filters from arguments
if [ -n "$ARG_BACKEND" ]; then
    BACKENDS=("$ARG_BACKEND")
fi
if [ -n "$ARG_NODES" ]; then
    NODE_COUNTS=("$ARG_NODES")
fi
if [ -n "$ARG_BANDWIDTH" ]; then
    BANDWIDTHS=("$ARG_BANDWIDTH")
fi

# Cleanup function
cleanup_environment() {
    log_info "Cleaning up Docker environment..."

    # Remove stale containers
    docker ps -aq --filter "name=clab-lab4" 2>/dev/null | xargs -r docker rm -f 2>/dev/null || true

    # Remove stale networks
    docker network ls --format '{{.Name}}' | grep -E "(lab4|clab-lab4)" | xargs -r docker network rm 2>/dev/null || true

    log_success "Environment cleaned"
}

# Pre-flight checks
preflight_checks() {
    log_info "Running pre-flight checks..."

    # Check required tools
    for cmd in docker containerlab python3; do
        if ! command -v $cmd &> /dev/null; then
            log_error "$cmd not found"
            exit 1
        fi
    done

    # Check Docker image
    if ! docker images | grep -q "hive-sim-node"; then
        log_error "hive-sim-node:latest image not found"
        echo "Run: docker build -t hive-sim-node:latest -f hive-sim/Dockerfile ."
        exit 1
    fi

    # Check disk space (require 10GB free)
    FREE_SPACE_GB=$(df -BG /var/lib/docker 2>/dev/null | tail -1 | awk '{print $4}' | tr -d 'G')
    if [ "${FREE_SPACE_GB:-0}" -lt 10 ]; then
        log_warning "Low disk space: ${FREE_SPACE_GB}GB free (recommend 10GB+)"
    fi

    # Load credentials
    if [ -f "../.env" ]; then
        set -a
        source ../.env
        set +a
        log_info "Loaded credentials from .env"
    fi

    log_success "Pre-flight checks passed"
}

# Run a single backend test (deploy, run, cleanup)
run_backend_test() {
    local BACKEND="$1"
    local NODES="$2"
    local BANDWIDTH="$3"
    local TIMESTAMP="$4"

    local TEST_NAME="lab4-${BACKEND}-${NODES}n-${BANDWIDTH}"
    local RESULTS_DIR="${RESULTS_BASE_DIR}/${TEST_NAME}-${TIMESTAMP}"

    log_info "Running: ${TEST_NAME}"

    # Create results directory
    mkdir -p "${RESULTS_DIR}/logs"

    # Use cached topology (cache key includes backend since it's baked into the file)
    local TOPO_CACHE_DIR="${RESULTS_BASE_DIR}/.topo-cache"
    mkdir -p "${TOPO_CACHE_DIR}"
    local TOPO_FILE="${TOPO_CACHE_DIR}/lab4-${BACKEND}-${NODES}n-${BANDWIDTH}.yaml"

    # Generate topology if not cached
    if [[ ! -f "${TOPO_FILE}" ]]; then
        log_info "  Generating topology..."
        python3 generate-lab4-hierarchical-topology.py \
            --nodes "${NODES}" \
            --bandwidth "${BANDWIDTH}" \
            --backend "${BACKEND}" \
            --output "${TOPO_FILE}" || {
            log_error "Failed to generate topology"
            echo "FAIL" > "${RESULTS_DIR}/status.txt"
            return 1
        }
    fi

    # Get lab name and expected nodes
    local LAB_NAME=$(grep '^name:' "$TOPO_FILE" | awk '{print $2}')
    local EXPECTED_NODES=$(grep -c "kind: linux" "$TOPO_FILE")
    echo "$LAB_NAME" > /tmp/lab4-current-lab-name

    log_info "  Deploying ${EXPECTED_NODES} nodes with BACKEND=${BACKEND}..."

    # Track deployment time
    local DEPLOY_START=$(date +%s.%N)

    # Substitute environment variables in topology file
    local TOPO_RESOLVED="${RESULTS_DIR}/topology-resolved.yaml"
    envsubst < "$TOPO_FILE" > "$TOPO_RESOLVED"

    # Deploy with resolved topology (no timeout - let it complete)
    if ! containerlab deploy -t "$TOPO_RESOLVED" --reconfigure > "${RESULTS_DIR}/deploy.log" 2>&1; then
        local DEPLOY_END=$(date +%s.%N)
        local DEPLOY_DURATION=$(echo "$DEPLOY_END - $DEPLOY_START" | bc)
        log_error "Deployment failed after ${DEPLOY_DURATION}s"
        tail -20 "${RESULTS_DIR}/deploy.log" 2>/dev/null || true
        echo "FAIL" > "${RESULTS_DIR}/status.txt"
        echo "deploy_duration_secs=${DEPLOY_DURATION}" > "${RESULTS_DIR}/timing.txt"
        echo "deploy_status=FAILED" >> "${RESULTS_DIR}/timing.txt"
        docker ps -aq --filter "name=clab-" | xargs -r docker rm -f > /dev/null 2>&1 || true
        return 1
    fi

    local DEPLOY_END=$(date +%s.%N)
    local DEPLOY_DURATION=$(echo "$DEPLOY_END - $DEPLOY_START" | bc)

    # Verify all containers are running
    local RUNNING=$(docker ps --filter "name=clab-${LAB_NAME}" --filter "status=running" -q 2>/dev/null | wc -l)
    if [[ "$RUNNING" -lt "$EXPECTED_NODES" ]]; then
        log_error "Only ${RUNNING}/${EXPECTED_NODES} containers running after deploy"
        echo "FAIL" > "${RESULTS_DIR}/status.txt"
        echo "deploy_duration_secs=${DEPLOY_DURATION}" > "${RESULTS_DIR}/timing.txt"
        echo "deploy_status=INCOMPLETE" >> "${RESULTS_DIR}/timing.txt"
        echo "expected_nodes=${EXPECTED_NODES}" >> "${RESULTS_DIR}/timing.txt"
        echo "running_nodes=${RUNNING}" >> "${RESULTS_DIR}/timing.txt"
        docker ps -aq --filter "name=clab-" | xargs -r docker rm -f > /dev/null 2>&1 || true
        return 1
    fi

    log_success "  Deployed ${RUNNING} containers in ${DEPLOY_DURATION}s"

    # Save timing info
    echo "deploy_duration_secs=${DEPLOY_DURATION}" > "${RESULTS_DIR}/timing.txt"
    echo "deploy_status=SUCCESS" >> "${RESULTS_DIR}/timing.txt"
    echo "expected_nodes=${EXPECTED_NODES}" >> "${RESULTS_DIR}/timing.txt"
    echo "running_nodes=${RUNNING}" >> "${RESULTS_DIR}/timing.txt"

    # Run test
    log_info "  Running test for ${TEST_DURATION_SECS}s..."
    local TEST_START=$(date +%s.%N)
    sleep "${TEST_DURATION_SECS}"
    local TEST_END=$(date +%s.%N)
    local TEST_DURATION=$(echo "$TEST_END - $TEST_START" | bc)
    echo "test_duration_secs=${TEST_DURATION}" >> "${RESULTS_DIR}/timing.txt"

    # Collect logs
    log_info "  Collecting logs..."
    collect_logs "${LAB_NAME}" "${RESULTS_DIR}/logs"

    # Extract metrics
    log_info "  Extracting metrics..."
    extract_test_metrics "${RESULTS_DIR}" > "${RESULTS_DIR}/metrics.csv"

    # Track cleanup time
    log_info "  Cleanup..."
    local CLEANUP_START=$(date +%s.%N)
    docker ps -aq --filter "name=clab-${LAB_NAME}" | xargs -r docker rm -f > /dev/null 2>&1 || true
    docker network ls --format '{{.Name}}' | grep "${LAB_NAME}" | xargs -r docker network rm 2>/dev/null || true
    local CLEANUP_END=$(date +%s.%N)
    local CLEANUP_DURATION=$(echo "$CLEANUP_END - $CLEANUP_START" | bc)
    echo "cleanup_duration_secs=${CLEANUP_DURATION}" >> "${RESULTS_DIR}/timing.txt"

    # Calculate total time
    local TOTAL_DURATION=$(echo "$DEPLOY_DURATION + $TEST_DURATION + $CLEANUP_DURATION" | bc)
    echo "total_duration_secs=${TOTAL_DURATION}" >> "${RESULTS_DIR}/timing.txt"

    echo "PASS" > "${RESULTS_DIR}/status.txt"
    log_success "Completed: ${TEST_NAME} (deploy: ${DEPLOY_DURATION}s, test: ${TEST_DURATION}s, cleanup: ${CLEANUP_DURATION}s)"
    return 0
}

# Collect logs from all relevant containers
collect_logs() {
    local LAB_NAME="$1"
    local LOG_DIR="$2"

    # Collect from all leader nodes
    for CONTAINER in $(docker ps --format '{{.Names}}' | grep "clab-${LAB_NAME}" | grep -E "(leader|commander)"); do
        local NODE_NAME=$(echo "$CONTAINER" | sed "s/clab-${LAB_NAME}-//")
        docker logs "$CONTAINER" 2>&1 > "${LOG_DIR}/${NODE_NAME}.log" 2>/dev/null || true
    done

    # Sample soldier log
    local SOLDIER=$(docker ps --format '{{.Names}}' | grep "clab-${LAB_NAME}" | grep "soldier" | head -1)
    if [ -n "$SOLDIER" ]; then
        docker logs "$SOLDIER" 2>&1 > "${LOG_DIR}/soldier-sample.log" 2>/dev/null || true
    fi
}

# Extract metrics from collected logs
extract_test_metrics() {
    local RESULTS_DIR="$1"
    local LOG_DIR="${RESULTS_DIR}/logs"

    echo "tier,event_type,metric,value"

    # Soldier to Squad latency (from squad leader logs)
    local S2S_P50=$(cat "${LOG_DIR}"/*squad*leader*.log 2>/dev/null | \
        grep 'METRICS:' | \
        grep '"event_type":"CRDTUpsert"' | \
        sed 's/.*"latency_ms":\([0-9.]*\).*/\1/' | \
        sort -n | \
        awk 'BEGIN{c=0} {a[c++]=$1} END{if(c>0) print a[int(c*0.5)]; else print 0}')

    local S2S_P95=$(cat "${LOG_DIR}"/*squad*leader*.log 2>/dev/null | \
        grep 'METRICS:' | \
        grep '"event_type":"CRDTUpsert"' | \
        sed 's/.*"latency_ms":\([0-9.]*\).*/\1/' | \
        sort -n | \
        awk 'BEGIN{c=0} {a[c++]=$1} END{if(c>0) print a[int(c*0.95)]; else print 0}')

    echo "soldier_to_squad,CRDTUpsert,p50_ms,${S2S_P50:-0}"
    echo "soldier_to_squad,CRDTUpsert,p95_ms,${S2S_P95:-0}"

    # Squad to Platoon latency (from platoon leader logs)
    local S2P_P50=$(cat "${LOG_DIR}"/*platoon*leader*.log 2>/dev/null | \
        grep 'METRICS:' | \
        grep '"event_type":"CRDTUpsert"' | \
        sed 's/.*"latency_ms":\([0-9.]*\).*/\1/' | \
        sort -n | \
        awk 'BEGIN{c=0} {a[c++]=$1} END{if(c>0) print a[int(c*0.5)]; else print 0}')

    local S2P_P95=$(cat "${LOG_DIR}"/*platoon*leader*.log 2>/dev/null | \
        grep 'METRICS:' | \
        grep '"event_type":"CRDTUpsert"' | \
        sed 's/.*"latency_ms":\([0-9.]*\).*/\1/' | \
        sort -n | \
        awk 'BEGIN{c=0} {a[c++]=$1} END{if(c>0) print a[int(c*0.95)]; else print 0}')

    echo "squad_to_platoon,CRDTUpsert,p50_ms,${S2P_P50:-0}"
    echo "squad_to_platoon,CRDTUpsert,p95_ms,${S2P_P95:-0}"

    # Total operations
    local TOTAL_OPS=$(cat "${LOG_DIR}"/*.log 2>/dev/null | grep -c 'METRICS:' || echo "0")
    echo "overall,operations,total_count,${TOTAL_OPS}"
}

# Main execution
main() {
    echo ""
    echo "========================================"
    echo " Lab 4 Backend Comparison Framework"
    echo "========================================"
    echo ""

    # Handle cleanup-only mode
    if [ "$CLEANUP_ONLY" = true ]; then
        cleanup_environment
        exit 0
    fi

    # Run pre-flight checks
    preflight_checks

    # Calculate total tests
    local TOTAL_TESTS=$((${#BACKENDS[@]} * ${#NODE_COUNTS[@]} * ${#BANDWIDTHS[@]}))
    local CURRENT_TEST=0
    local TIMESTAMP=$(date +%Y%m%d-%H%M%S)

    echo ""
    echo "Test Matrix:"
    echo "  Backends: ${BACKENDS[*]}"
    echo "  Nodes: ${NODE_COUNTS[*]}"
    echo "  Bandwidths: ${BANDWIDTHS[*]}"
    echo "  Duration: ${TEST_DURATION_SECS}s per test"
    echo "  Total tests: ${TOTAL_TESTS}"
    echo ""

    if [ "$DRY_RUN" = true ]; then
        echo "DRY RUN - Would execute:"
        for BACKEND in "${BACKENDS[@]}"; do
            for NODES in "${NODE_COUNTS[@]}"; do
                for BANDWIDTH in "${BANDWIDTHS[@]}"; do
                    echo "  BACKEND=${BACKEND} NODES=${NODES} BANDWIDTH=${BANDWIDTH}"
                done
            done
        done
        exit 0
    fi

    # Clean up before starting
    cleanup_environment

    # Create results summary file
    local SUMMARY_FILE="${RESULTS_BASE_DIR}/lab4-comparison-${TIMESTAMP}.csv"
    mkdir -p "$(dirname "$SUMMARY_FILE")"
    echo "backend,nodes,bandwidth,status,deploy_secs,s2s_p50,s2s_p95,s2p_p50,s2p_p95,total_ops" > "$SUMMARY_FILE"

    # Run test matrix - each test deploys its own topology (topology files are cached)
    for NODES in "${NODE_COUNTS[@]}"; do
        for BANDWIDTH in "${BANDWIDTHS[@]}"; do
            for BACKEND in "${BACKENDS[@]}"; do
                CURRENT_TEST=$((CURRENT_TEST + 1))
                echo ""
                echo "╔══════════════════════════════════════════════════════════════╗"
                echo "║  Test ${CURRENT_TEST}/${TOTAL_TESTS}: ${BACKEND} @ ${NODES}n, ${BANDWIDTH}"
                echo "╚══════════════════════════════════════════════════════════════╝"

                local TEST_NAME="lab4-${BACKEND}-${NODES}n-${BANDWIDTH}"
                local TEST_RESULTS_DIR="${RESULTS_BASE_DIR}/${TEST_NAME}-${TIMESTAMP}"

                if run_backend_test "$BACKEND" "$NODES" "$BANDWIDTH" "$TIMESTAMP"; then
                    # Extract summary metrics and timing
                    local METRICS_FILE="${TEST_RESULTS_DIR}/metrics.csv"
                    local TIMING_FILE="${TEST_RESULTS_DIR}/timing.txt"
                    local DEPLOY_SECS=$(grep "deploy_duration_secs" "$TIMING_FILE" 2>/dev/null | cut -d= -f2 | cut -d. -f1)
                    if [ -f "$METRICS_FILE" ]; then
                        local S2S_P50=$(grep "soldier_to_squad.*p50" "$METRICS_FILE" | cut -d, -f4)
                        local S2S_P95=$(grep "soldier_to_squad.*p95" "$METRICS_FILE" | cut -d, -f4)
                        local S2P_P50=$(grep "squad_to_platoon.*p50" "$METRICS_FILE" | cut -d, -f4)
                        local S2P_P95=$(grep "squad_to_platoon.*p95" "$METRICS_FILE" | cut -d, -f4)
                        local TOTAL_OPS=$(grep "overall.*total_count" "$METRICS_FILE" | cut -d, -f4)
                        echo "${BACKEND},${NODES},${BANDWIDTH},PASS,${DEPLOY_SECS:-0},${S2S_P50:-0},${S2S_P95:-0},${S2P_P50:-0},${S2P_P95:-0},${TOTAL_OPS:-0}" >> "$SUMMARY_FILE"
                    else
                        echo "${BACKEND},${NODES},${BANDWIDTH},PASS,${DEPLOY_SECS:-0},0,0,0,0,0" >> "$SUMMARY_FILE"
                    fi
                else
                    # Try to get deploy time even on failure
                    local TIMING_FILE="${TEST_RESULTS_DIR}/timing.txt"
                    local DEPLOY_SECS=$(grep "deploy_duration_secs" "$TIMING_FILE" 2>/dev/null | cut -d= -f2 | cut -d. -f1)
                    echo "${BACKEND},${NODES},${BANDWIDTH},FAIL,${DEPLOY_SECS:-0},0,0,0,0,0" >> "$SUMMARY_FILE"
                    if [[ "$CONTINUE_ON_ERROR" == "true" ]]; then
                        log_warning "Test failed, continuing (--continue-on-error set)..."
                    else
                        log_error "Test failed! Aborting remaining tests."
                        echo ""
                        echo "Partial results saved to: ${SUMMARY_FILE}"
                        echo "To continue despite failures, use: --continue-on-error"
                        # Cleanup before exit
                        docker ps -aq --filter "name=clab-" | xargs -r docker rm -f > /dev/null 2>&1 || true
                        exit 1
                    fi
                fi
            done
        done
    done

    # Print summary
    echo ""
    echo "========================================"
    echo " Test Summary"
    echo "========================================"
    echo ""
    echo "Results saved to: ${SUMMARY_FILE}"
    echo ""
    cat "$SUMMARY_FILE" | column -t -s,
    echo ""

    local PASSED=$(grep -c ",PASS," "$SUMMARY_FILE" || echo "0")
    local FAILED=$(grep -c ",FAIL," "$SUMMARY_FILE" || echo "0")
    echo "Passed: ${PASSED} / Failed: ${FAILED}"

    # Print deployment timing summary
    echo ""
    echo "Deployment Timing by Node Count:"
    for nodes in 24 48 96 384; do
        local TIMES=$(grep ",${nodes}," "$SUMMARY_FILE" | grep ",PASS," | cut -d, -f5 | tr '\n' ' ')
        if [ -n "$TIMES" ]; then
            local AVG=$(echo "$TIMES" | tr ' ' '\n' | awk '{sum+=$1; n++} END {if(n>0) printf "%.1f", sum/n}')
            local MIN=$(echo "$TIMES" | tr ' ' '\n' | sort -n | head -1)
            local MAX=$(echo "$TIMES" | tr ' ' '\n' | sort -n | tail -1)
            echo "  ${nodes} nodes: avg=${AVG}s min=${MIN}s max=${MAX}s"
        fi
    done

    # Run analysis sweep on all collected data
    echo ""
    echo "========================================"
    echo " Analysis Sweep"
    echo "========================================"
    run_analysis_sweep "${TIMESTAMP}"

    # Generate comparison report
    generate_comparison_report "${SUMMARY_FILE}" "${RESULTS_BASE_DIR}/lab4-comparison-report-${TIMESTAMP}.md"
}

# Run analysis on all result directories from this run
run_analysis_sweep() {
    local TIMESTAMP="$1"

    echo ""
    echo "Analyzing all results from run ${TIMESTAMP}..."

    local ANALYSIS_COUNT=0
    local ANALYSIS_FAILED=0

    for RESULTS_DIR in "${RESULTS_BASE_DIR}"/lab4-*-${TIMESTAMP}; do
        if [[ -d "$RESULTS_DIR" && -f "${RESULTS_DIR}/status.txt" ]]; then
            local TEST_NAME=$(basename "$RESULTS_DIR")
            echo -n "  Analyzing ${TEST_NAME}... "

            if [[ -x "${SCRIPT_DIR}/process-lab4-metrics.sh" ]]; then
                if "${SCRIPT_DIR}/process-lab4-metrics.sh" "${RESULTS_DIR}" > "${RESULTS_DIR}/analysis-report.txt" 2>&1; then
                    echo "OK"
                    ANALYSIS_COUNT=$((ANALYSIS_COUNT + 1))
                else
                    echo "WARN"
                    ANALYSIS_FAILED=$((ANALYSIS_FAILED + 1))
                fi
            else
                echo "SKIP (no analyzer)"
            fi
        fi
    done

    echo ""
    echo "Analysis complete: ${ANALYSIS_COUNT} succeeded, ${ANALYSIS_FAILED} with warnings"
}

# Generate markdown comparison report
generate_comparison_report() {
    local SUMMARY_CSV="$1"
    local REPORT_FILE="$2"

    echo ""
    echo "========================================"
    echo " Generating Comparison Report"
    echo "========================================"

    cat > "$REPORT_FILE" << 'HEADER'
# Lab 4: Backend Comparison Report

## Overview

This report compares Ditto and Automerge backends across different node counts and bandwidth configurations.

HEADER

    echo "## Test Matrix Results" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "| Backend | Nodes | Bandwidth | Status | Deploy(s) | S→Squad P50 | S→Squad P95 | Squad→Platoon P50 | Squad→Platoon P95 |" >> "$REPORT_FILE"
    echo "|---------|-------|-----------|--------|-----------|-------------|-------------|-------------------|-------------------|" >> "$REPORT_FILE"

    # Skip header line, format each row
    tail -n +2 "$SUMMARY_CSV" | while IFS=, read -r backend nodes bw status deploy_secs s2s_p50 s2s_p95 s2p_p50 s2p_p95 ops; do
        echo "| $backend | $nodes | $bw | $status | ${deploy_secs}s | ${s2s_p50}ms | ${s2s_p95}ms | ${s2p_p50}ms | ${s2p_p95}ms |" >> "$REPORT_FILE"
    done

    # Deployment timing summary
    echo "" >> "$REPORT_FILE"
    echo "## Deployment Timing Analysis" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "| Nodes | Avg Deploy Time |" >> "$REPORT_FILE"
    echo "|-------|-----------------|" >> "$REPORT_FILE"
    for nodes in 24 48 96 384; do
        local AVG_DEPLOY=$(grep ",${nodes}," "$SUMMARY_CSV" | grep ",PASS," | cut -d, -f5 | awk '{sum+=$1; n++} END {if(n>0) printf "%.0f", sum/n; else print "N/A"}')
        echo "| $nodes | ${AVG_DEPLOY}s |" >> "$REPORT_FILE"
    done

    echo "" >> "$REPORT_FILE"
    echo "## Backend Comparison by Node Count" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    for nodes in 24 48 96 384; do
        echo "### ${nodes} Nodes" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"

        local DITTO_P95=$(grep "^ditto,${nodes}," "$SUMMARY_CSV" | grep "1gbps" | cut -d, -f6)
        local AUTOMERGE_P95=$(grep "^automerge,${nodes}," "$SUMMARY_CSV" | grep "1gbps" | cut -d, -f6)

        if [[ -n "$DITTO_P95" && -n "$AUTOMERGE_P95" ]]; then
            echo "- **Ditto** Soldier→Squad P95: ${DITTO_P95}ms" >> "$REPORT_FILE"
            echo "- **Automerge** Soldier→Squad P95: ${AUTOMERGE_P95}ms" >> "$REPORT_FILE"

            # Calculate winner
            if (( $(echo "$DITTO_P95 < $AUTOMERGE_P95" | bc -l 2>/dev/null || echo 0) )); then
                echo "- **Winner**: Ditto ($(echo "scale=1; $AUTOMERGE_P95 - $DITTO_P95" | bc)ms faster)" >> "$REPORT_FILE"
            elif (( $(echo "$AUTOMERGE_P95 < $DITTO_P95" | bc -l 2>/dev/null || echo 0) )); then
                echo "- **Winner**: Automerge ($(echo "scale=1; $DITTO_P95 - $AUTOMERGE_P95" | bc)ms faster)" >> "$REPORT_FILE"
            else
                echo "- **Result**: Tied" >> "$REPORT_FILE"
            fi
        else
            echo "- Data not available for comparison" >> "$REPORT_FILE"
        fi
        echo "" >> "$REPORT_FILE"
    done

    echo "## Bandwidth Impact" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "| Bandwidth | Automerge P95 (96n) | Ditto P95 (96n) |" >> "$REPORT_FILE"
    echo "|-----------|---------------------|-----------------|" >> "$REPORT_FILE"

    for bw in 1gbps 100mbps 1mbps 256kbps; do
        local AM=$(grep "^automerge,96,${bw}" "$SUMMARY_CSV" | cut -d, -f6)
        local DT=$(grep "^ditto,96,${bw}" "$SUMMARY_CSV" | cut -d, -f6)
        echo "| $bw | ${AM:-N/A}ms | ${DT:-N/A}ms |" >> "$REPORT_FILE"
    done

    echo "" >> "$REPORT_FILE"
    echo "---" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "*Generated: $(date)*" >> "$REPORT_FILE"

    log_success "Comparison report: ${REPORT_FILE}"
    echo ""
    cat "$REPORT_FILE"
}

main "$@"
